version: '3.8'

networks:
  nlab:
    name: nlab
volumes:
  vlab:
    name: vlab

services:
  lab:
    image: ilab
    container_name: clab
    build: .
    volumes:
      - vlab:/var/www/html
      - ./lab:/root/lab
      - ./zshrc:/root/.zshrc
      - ./zsh_history:/root/.zsh_history
    networks:
      - nlab